P1

ft_calloc; //ACHO QUE CONSIGO CAZER SE EU ESTUDAR MAIS.

ft_memmove; //NÃO SEI COMO FUNCIONA.

ft_strlcat; 
ft_strlcpy;
//NÃO VEJO SENTIDO NENHUM NESSAS FUNÇÕES.
//JÁ TENTEI FAZER MAS FALHEI MISERAVELMENTE DURANTE HORAS,
//ENTÃO DEIXEI-A PARA FAZER DEPOIS QUE EU PEDIR AJUDA.

ft_strnstr; //NÃO ENTENDI COMO FUNCIONA.



P2

ft_itoa; //NÃO ENTENDI O FUNCIONAMENTO
	 //NÃO SEI EM QUE ELA SE DIFERE DA PUTNBR.

ft_split; //DEIXEI PARA SER UMA DAS ÚLTIMAS, MAS JÁ ENTENDI O CONCEITO.

ft_strmapi; //NÃO ENTENDI NADA.
	    //NÃO SOUBERAM ME EXPLICAR, APESAR DE JÁ TEREM FEITO.

ft_striteri; //MESMO DILETA DA FT_STRMAPI.

ft_strtrim; //TENTEI FAZER USANDO A SUBSTR MAS,
	    //DEVIDO EU NÃO ENTENDER O MODO COMO ELA RETORNA,
	    //A EXECUÇÃO FOI UM FRACASSO.
